services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports: ["1433:1433"]
    volumes: ["sql_data:/var/opt/mssql"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
  rabbitmq:
    image: rabbitmq:4.3-management
    ports: ["5672:5672", "15672:15672"]
    volumes: ["rabbit_data:/var/lib/rabbitmq"]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    environment:
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=SolicitudesDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False"
      Jwt__Key: "CAMBIAR-ESTA-CLAVE-POR-UNA-DE-32-CARACTERES-MINIMO-SEGURA"
      Security__EncryptionKey: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: guest
      RabbitMQ__Password: guest
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports: ["5000:8080"]
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    environment:
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=SolicitudesDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: guest
      RabbitMQ__Password: guest
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports: ["4200:80"]
    depends_on: [api]
volumes:
  sql_data:
  rabbit_data:
